

export const AUTH_EBAY_CONSENT_REQUEST = "AUTH_EBAY_CONSENT_REQUEST";
//export const AUTH_EBAY_CONSENT_SUCCESS = "AUTH_EBAY_CONSENT_SUCCESS";
//export const AUTH_EBAY_CONSENT_FAIL = "AUTH_EBAY_CONSENT_FAIL";

export const AUTH_EBAY = "AUTH_EBAY";
export const AUTH_EBAY_REQUEST = "AUTH_EBAY_REQUEST";
export const AUTH_EBAY_SUCCESS = "AUTH_EBAY_SUCCESS";
export const AUTH_EBAY_FAIL = "AUTH_EBAY_FAIL";
export const AUTH_EBAY_RESET = "AUTH_EBAY_RESET";

export const LOAD_EBAY_SUPER_CATEGORIES = "LOAD_EBAY_SUPER_CATEGORIES";
export const LOAD_EBAY_SUPER_CATEGORIES_REQUEST = "LOAD_EBAY_SUPER_CATEGORIES_REQUEST";
export const LOAD_EBAY_SUPER_CATEGORIES_SUCCESS = "LOAD_EBAY_SUPER_CATEGORIES_SUCCESS";
export const LOAD_EBAY_SUPER_CATEGORIES_CARDS_SUCCESS = "LOAD_EBAY_SUPER_CATEGORIES_CARDS_SUCCESS";
export const LOAD_EBAY_SUPER_CATEGORIES_FAIL= "LOAD_EBAY_SUPER_CATEGORIES_FAIL";

export const LOAD_EBAY_ITEMS_CAROUSEL = "LOAD_EBAY_ITEMS_CAROUSEL";
export const LOAD_EBAY_ITEMS_CAROUSEL_REQUEST = "LOAD_EBAY_ITEMS_CAROUSEL_REQUEST";
export const LOAD_EBAY_ITEMS_CAROUSEL_SUCCESS = "LOAD_EBAY_ITEMS_CAROUSEL_SUCCESS";
export const LOAD_EBAY_ITEMS_CAROUSEL_FAIL= "LOAD_EBAY_ITEMS_CAROUSEL_FAIL";