

export const AUTH_EBAY_CONSENT_REQUEST = "AUTH_EBAY_CONSENT_REQUEST";
export const AUTH_EBAY_CONSENT_SUCCESS = "AUTH_EBAY_CONSENT_SUCCESS";
export const AUTH_EBAY_CONSENT_FAIL = "AUTH_EBAY_CONSENT_FAIL";

export const AUTH_EBAY = "AUTH_EBAY";
export const AUTH_EBAY_REQUEST = "AUTH_EBAY_REQUEST";
export const AUTH_EBAY_SUCCESS = "AUTH_EBAY_SUCCESS";
export const AUTH_EBAY_FAIL = "AUTH_EBAY_FAIL";