
export const USER_AUTH = "USER_AUTH";
export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_AUTH_RESET = "USER_AUTH_RESET";

export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const USER_LOGIN_LISTENER = "USER_LOGIN_LISTENER";
export const USER_LOGIN_LISTENER_REQUEST = "USER_LOGIN_LISTENER_REQUEST";
export const USER_LOGIN_LISTENER_SUCCESS = "USER_LOGIN_LISTENER_SUCCESS";
export const USER_LOGIN_LISTENER_FAIL = "USER_LOGIN_LISTENER_FAIL";

